In [1]:
import numpy as np
import pandas as pd
import requests
from bs4 import BeautifulSoup
import re
import warnings
warnings.filterwarnings('ignore')

In [2]:
hotel=[]
price=[]
location=[]
km=[]
rating=[]
city=[]
discount=[]
Star_rating=[]
Ratedby=[]
Overall=[]
original_price=[]
for i in range(1,7):
    url=f"https://www.oyorooms.com/hotels-in-kolkata/?page={i}"
    link=requests.get(url)
    a=requests.get(url,headers = {'User-Agent':'Mozilla/5.0'})
    content=a.text
    soup=BeautifulSoup(content)
    
    container=soup.find_all("div",class_="hotelCardListing__descriptionWrapper")
    
#     for i in container:
#         print(i.text)
    for i in container:
        a=i.find("a",class_="c-nn640c u-width100")
        text=a.text
        hotel.append(text)
    for i in container:
        b=i.find("div",class_="d-body-lg listingHotelDescription__hotelAddress")
        text=b.text
        #print(text)
        regex=re.findall("(.*),",text)
        
        if regex:
            location.append(regex[0])
        else:
            location.append(np.nan)
        
        regex1=re.findall(",\s(Kolkata).",text)
        #print(regex1)
        if regex1:
            city.append(regex1[0])
        else:
            city.append("Kolkata")
        
        regex2=re.findall("(\d\.\d\skm)",text)
        #print(regex1)
        if regex2:
            km.append(regex2[0])
        else:
            km.append(np.nan)
    for i in container:
        b=i.find('div',class_='hotelRating')
        text=b.text
        regex=re.findall("\d\.\d",text)
        if regex:
            Star_rating.append(regex[0])
        else:
            Star_rating.append(np.nan)
        regex2=re.findall("\((\d+\s)",text)
        if regex2:
            Ratedby.append(regex2[0])
        else:
            Ratedby.append(np.nan)
        regex3=re.findall('.(\w+.\w+$)',text)
        if regex3:
            Overall.append(regex3[0])
        else:
            Overall.append(np.nan)
    for i in container:
        b=i.find('span',class_="listingPrice__finalPrice")
        text=b.text
        regex=re.findall("\d+",text)
        if regex:
            price.append(regex[0])
        else:
            price.append(np.nan)
    for i in container:
        b=i.find("span",class_="listingPrice__slashedPrice d-body-lg")
        text=b.text
        regex=re.findall("\d+",text)
        if regex:
            original_price.append(regex[0])
        else:
            original_price.append(np.nan)
    for i in container:
        b=i.find('span',class_="listingPrice__percentage")
        text=b.text
        regex=re.findall("\d+",text)
        if regex:
            discount.append(regex[0])
        else:
            discount.append(np.nan)

In [3]:
oyo_kolkata=pd.DataFrame({'Hotel_Name':hotel,'location':location,'City':city,"Star_rating":Star_rating,"Ratedby":Ratedby,"Ratingsummary":Overall,"Original_price_in(₹)":original_price,"Discount_in(%)":discount,"Final_price_in(₹)":price})

In [4]:
oyo_kolkata

,Hotel_Name,location,City,Star_rating,Ratedby,Ratingsummary,Original_price_in(₹),Discount_in(%),Final_price_in(₹)
0,SPOT ON Dalhousie Guest House Near Howrah Bridge,Stand Road,Kolkata,4.5,3375,Excellent,2833,83,454
1,OYO White Palace Hotel & Resort New Alipore Ne...,Opposite New Alipore Residency,Kolkata,4.0,859,Very Good,3309,81,599
2,Flagship Royal Palace,"Near Acropolis Mall, Purba Abasan",Kolkata,4.3,1820,Very Good,2715,81,499
3,Flagship Royal Plaza Near Acropolis Mall,"Near GST Bhawan, Ruby",Kolkata,4.3,2008,Very Good,2366,76,559
4,Collection O Hotel Green Leaf Near Acropolis Mall,Kasba,Kolkata,4.1,1303,Very Good,3171,81,599
...,...,...,...,...,...,...,...,...,...
115,OYO Flagship 70403 Chinar Inn,Chinar parknull,Kolkata,NaN,NaN,NaN,2755,68,868
116,Flagship Relax View Dumdum Park Near City Cent...,Dum Dum Park,Kolkata,2.5,97,Fair,2988,68,941
117,OYO Townhouse 424 Beck Bagan Ballygunge Near B...,"Near Quest Mall, Karaya Road",Kolkata,3.5,366,Good,5064,65,1772
118,Townhouse OAK Hotel Tahoura International Near...,Repon Street,Kolkata,3.7,116,Good,7422,65,2598
119,Flagship Amaris Stay Hub VIP Bazar Near Scienc...,"171D/1F/2, 49 Picnic Garden Road, VIP Bazar, O...",Kolkata,3.4,473,Fair,4572,65,1600

In [5]:
oyo_kolkata.isnull().sum()

Hotel_Name              0
location                7
City                    0
Star_rating             4
Ratedby                 4
Ratingsummary           4
Original_price_in(₹)    0
Discount_in(%)          0
Final_price_in(₹)       0
dtype: int64

In [6]:
oyo_kolkata["Star_rating"]=oyo_kolkata["Star_rating"].astype(float)

In [7]:
oyo_kolkata["Star_rating"].mean()

3.9094827586206886

In [8]:
oyo_kolkata["Star_rating"]=oyo_kolkata["Star_rating"].fillna(3.8)

In [9]:
oyo_kolkata["Ratedby"]=oyo_kolkata["Ratedby"].astype(float)

In [10]:
oyo_kolkata["Ratedby"]=oyo_kolkata["Ratedby"].fillna(oyo_kolkata["Ratedby"].mean())

In [11]:
oyo_kolkata["Ratedby"]=oyo_kolkata["Ratedby"].astype(int)

In [12]:
oyo_kolkata["Final_price_in(₹)"]=oyo_kolkata["Final_price_in(₹)"].astype(int)

In [13]:
oyo_kolkata["Original_price_in(₹)"]=oyo_kolkata["Original_price_in(₹)"].astype(int)

In [14]:
oyo_kolkata["Discount_in(%)"]=oyo_kolkata["Discount_in(%)"].astype(int)

In [15]:
#Filling the missing values using Mode

x=oyo_kolkata.Ratingsummary.mode()[0]
oyo_kolkata.Ratingsummary.fillna(x,inplace=True)

In [16]:
oyo_kolkata.isnull().sum()

Hotel_Name              0
location                7
City                    0
Star_rating             0
Ratedby                 0
Ratingsummary           0
Original_price_in(₹)    0
Discount_in(%)          0
Final_price_in(₹)       0
dtype: int64

In [17]:
oyo_kolkata.dropna(inplace=True)

In [18]:
oyo_kolkata.isnull().sum()

Hotel_Name              0
location                0
City                    0
Star_rating             0
Ratedby                 0
Ratingsummary           0
Original_price_in(₹)    0
Discount_in(%)          0
Final_price_in(₹)       0
dtype: int64

In [19]:
oyo_kolkata

,Hotel_Name,location,City,Star_rating,Ratedby,Ratingsummary,Original_price_in(₹),Discount_in(%),Final_price_in(₹)
0,SPOT ON Dalhousie Guest House Near Howrah Bridge,Stand Road,Kolkata,4.5,3375,Excellent,2833,83,454
1,OYO White Palace Hotel & Resort New Alipore Ne...,Opposite New Alipore Residency,Kolkata,4.0,859,Very Good,3309,81,599
2,Flagship Royal Palace,"Near Acropolis Mall, Purba Abasan",Kolkata,4.3,1820,Very Good,2715,81,499
3,Flagship Royal Plaza Near Acropolis Mall,"Near GST Bhawan, Ruby",Kolkata,4.3,2008,Very Good,2366,76,559
4,Collection O Hotel Green Leaf Near Acropolis Mall,Kasba,Kolkata,4.1,1303,Very Good,3171,81,599
...,...,...,...,...,...,...,...,...,...
115,OYO Flagship 70403 Chinar Inn,Chinar parknull,Kolkata,3.8,1111,Very Good,2755,68,868
116,Flagship Relax View Dumdum Park Near City Cent...,Dum Dum Park,Kolkata,2.5,97,Fair,2988,68,941
117,OYO Townhouse 424 Beck Bagan Ballygunge Near B...,"Near Quest Mall, Karaya Road",Kolkata,3.5,366,Good,5064,65,1772
118,Townhouse OAK Hotel Tahoura International Near...,Repon Street,Kolkata,3.7,116,Good,7422,65,2598
119,Flagship Amaris Stay Hub VIP Bazar Near Scienc...,"171D/1F/2, 49 Picnic Garden Road, VIP Bazar, O...",Kolkata,3.4,473,Fair,4572,65,1600

In [20]:
oyo_kolkata.to_csv("oyokolkata10")